-- --------------------------------------------------------
-- Konak:                        www.oyunde.com
-- Server version:               5.1.56-community - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL Sürüm:               7.0.0.4316
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping database structure for oyunde
DROP DATABASE IF EXISTS `oyunde`;
CREATE DATABASE IF NOT EXISTS `oyunde` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `oyunde`;


-- Dumping structure for table oyunde.kategoriler
DROP TABLE IF EXISTS `kategoriler`;
CREATE TABLE IF NOT EXISTS `kategoriler` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `kad` char(255) CHARACTER SET latin5 DEFAULT NULL,
  `isapi` char(255) CHARACTER SET latin5 DEFAULT NULL,
  `aciklama` varchar(2000) CHARACTER SET latin5 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=latin1;

-- Dumping data for table oyunde.kategoriler: ~16 rows (approximately)
DELETE FROM `kategoriler`;
/*!40000 ALTER TABLE `kategoriler` DISABLE KEYS */;
INSERT INTO `kategoriler` (`id`, `kad`, `isapi`, `aciklama`) VALUES
	(1, 'Aksiyon', 'aksiyon', '&nbsp;&nbsp;Aksiyon kategorisindeki  oyunlar ile aksiyonun sonuna kadar yaşayın, bu kategorideki oyunlar ile tüm günün yorgunluğunu üstünüzden atıcaksınız\r\nen yeni aksiyon oyunlarını , aksiyon kategorisi altında bulabilirsiniz.'),
	(2, 'Macera', 'macera', '&nbsp;&nbsp;Macera mı arıyorsunuz ? Macera kategorisindeki oyunlar tam size göre çünkü macerası yüksek tüm oyunlar macera kategorisi altında sizleri beklemektedir.\r\nTek yapmanız gereken oyunu seçmen ve yeni maceralara atılmak.'),
	(3, 'Yarış', 'yaris', '&nbsp;&nbsp;Yarışçı ruhunuzu dizginlemeden geliştirmek mi istiyorsunuz yarış kategorisindeki tüm oyunlar tam sizlere göre tek yapmanız gerek bir oyun seçmek ve bir yarıştan diğer bir yarışa geçmek'),
	(4, 'Kız', 'kiz', '&nbsp;&nbsp;Kız oyunlar ile en yeni ve en zevkli kız oyunlarına ücretsiz olarak bu kategori altında ulaşabilirsiniz.\r\nAyrıca sevdiğinz kız oyunlarını listenizde toplayabilir tekrar aramakla uğraşmazsınız.'),
	(5, 'Puzzle', 'Puzzle', '&nbsp;&nbsp;Puzzle oyunları ile stresiniz atabilirsiniz ayrıca puzzle oyunları ile zevkli saatler geçirebilirsiniz.Puzzle oyunlarına ücretsiz olarak bu kategori altında ulaşabilirsiniz. En yeni  ve en güncel puzzle oyunları daima oyunde.com da'),
	(6, 'Silah', 'Silah', '&nbsp;&nbsp;Silah oyunları ile aksiyonun sonuna kadar yaşayın ,en yeni ve en güzel silah oyunları bu kategori altında ulaşabilir ayrıca oyun listemde kendi silah oyunları listenizi oluşturabilirsiniz'),
	(7, 'Beceri', 'Beceri', '&nbsp;&nbsp;Becerinizi kanıtlamak mı istiyorsunuz bu kategorideki oyunlar tam size çünkü en çok beceri isteyen oyunları bu kategoride sizleri bekliyor'),
	(8, 'Strateji', 'Strateji', '&nbsp;&nbsp;Tam bir strateji uzmanımısınız o zaman bu strateji oyunları kategorisindeki oyunlar tam size göre çünkü en yeni ve en güncel strateji oyunları bu kategori altında ulaşabilirisiniz.'),
	(9, 'İki kişilik', 'ikikisilik', '&nbsp;&nbsp;Arkadaşınızla karşılıklı oyun mu oynamak istiyorsunuz,o zaman iki kişilik oyunlar kategorisindeki oyunlar tam size göre arkadaşınızla ortak oyunlar oynayabilir ayrıca oyun listenizden iki kişilik oyun listenizi oluşturabilirsiniz.'),
	(11, 'Araba', 'araba', '&nbsp;&nbsp;Araba sürmek  en büyük zevkiniz mi ? O zaman araba oyunları kategorisideki oyunlar tam size göre çünkü bu kategorideki oyunların hepsi en yeni oyunlar ve aksiyonu bol olan oyunlardır.Araba oyunları kategorisindeki oyunlar ile hız sınırlarını zorlayın'),
	(12, 'Meb Oyunları', 'meboyunlari', '&nbsp;&nbsp;En yeni meb oyunularını bu kategoride oynayabilirsiniz.Sizin için en güncel ve en yeni meb oyunlarını bu kategoride topladık'),
	(13, '3 Boyutlu', '3Boyutlu', '&nbsp;&nbsp;3 boyutlu oyunlar ile gerçekciliği yaşayın , 2 boyutlu oyunlardan sıkıldıysanız 3 boyutlu oyunlar kategorisindeki oyunlar tam size göre hadi vakit kaybetmeden 3 boyutlu oyunlar ile eglencenin keyfine varın.'),
	(14, 'Spor', 'Spor', '&nbsp;&nbsp;Spor oyunlarına meraklıysanız spor kategorisinde ki oyunlar tam size göre spor oyunlarında çeşitli spor dallarında yapılmış olan oyunları oynayabilir arkadaşlarınıza karşı spor oyunları oynayabilirsiniz'),
	(15, 'Balon Patlatma', 'balonpatlatma', '&nbsp;&nbsp;Canınız sıkılıyorsa balon patlatma oyunları tam size göre balon patlama oyunları adında anlaşılacagı gibi balonları patlattıkça puan kazanmaktasını.Ve böyle bir balon patlama seviyesine geçmektesiniz.'),
	(16, 'Boyama', 'boyama', '&nbsp;&nbsp;Boyama yapmak yada kitap boyamak hoşunuza gidiyorsa bu kategori tam size göre bu kategoride boyama oyunlarının en yenilerine ve en güzellerine ulaşabilirsiniz.Yapmanız gereken tek şey boyama oyununu seçmek ve boyamaya başlamak'),
	(17, 'Ameliyat Oyunları', 'ameliyat', '&nbsp;&nbsp;Doktorculuk oyunları ilginizimi çekiyor o zaman bu kategorideki oyunlar tam size göre tek yapmanız gereken oyununuzu seçmek ve ameliyata başlamak');
/*!40000 ALTER TABLE `kategoriler` ENABLE KEYS */;


-- Dumping structure for table oyunde.konular
DROP TABLE IF EXISTS `konular`;
CREATE TABLE IF NOT EXISTS `konular` (
  `baslik` char(255) CHARACTER SET latin5 DEFAULT NULL,
  `icerik` varchar(2500) CHARACTER SET latin5 DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `isapi` char(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table oyunde.konular: ~3 rows (approximately)
DELETE FROM `konular`;
/*!40000 ALTER TABLE `konular` DISABLE KEYS */;
INSERT INTO `konular` (`baslik`, `icerik`, `id`, `isapi`) VALUES
	('En yeni oyunlar', '<p>\r\n	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Oyunde olarak sizler i&ccedil;in <a href="http://www.oyunde.com"><strong>oyun oyna</strong></a>yabileceginiz en yeni oyunları &nbsp;tek sitede topluyoruz sizlerin tek yapmanız gereken kategorilerden istediğiniz oyunu se&ccedil;mek ve eğlencenin zevkine varmak.Oyunde &uuml;zerindee toplamda 15 kategori bulunmaktadır bunlar</p>\r\n<p>\r\n	&nbsp;</p>\r\n<ul>\r\n	<li>\r\n		Aksiyon</li>\r\n	<li>\r\n		Macera</li>\r\n	<li>\r\n		Yarış</li>\r\n	<li>\r\n		Kız</li>\r\n	<li>\r\n		Puzzle</li>\r\n	<li>\r\n		Silah</li>\r\n	<li>\r\n		Beceri</li>\r\n	<li>\r\n		Strateji</li>\r\n	<li>\r\n		İki kişilik</li>\r\n	<li>\r\n		Araba</li>\r\n	<li>\r\n		Meb Oyunları</li>\r\n	<li>\r\n		3 Boyutlu</li>\r\n	<li>\r\n		Spor</li>\r\n	<li>\r\n		Balon Patlatma</li>\r\n	<li>\r\n		Boyama</li>\r\n</ul>\r\n<p>\r\n	Ve her kategoride<a href="http://www.oyunde.com" name="Oyun oyna"><strong> oyun oyna</strong></a>bileceginiz en yeni y&uuml;zlerce oyunu sizlere sunmaktayız.</p>\r\n', 3, 'en-yeni-oyunlar'),
	('Oyun oynamanın incelikleri', '<p>\r\n	Her oyuncunun kendine &ouml;zg&uuml; bir stili vardır diye boşuna demiyorlar &ccedil;&uuml;nk&uuml; dedikleri gibi her oyuncunun kendie &ouml;zg&uuml;n <a href="http://www.oyunde.com"><strong>oyun oyna</strong></a>ma şekli vardır ve oyun oynama stili g&ouml;re oyunda y&uuml;kselirler.İşte &nbsp;bu y&uuml;zden herhangi bir oyun yada oyunları oynarken mutlaka kendinize bir yol oluşturun ve o şekilde oyun oynayın.</p>\r\n', 4, 'oyun-oynamanin-incelikleri'),
	('Oyun Oynama İpuçları', '<p>\r\n	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Bir oyunda başarılı olmak istiyorsanız mutlaka ama mutlaka oyunua konsantre olmanız şarttır &ccedil;&uuml;nk&uuml; oyunu oyun yapan o anki konsantredir.Eğer bir b&ouml;l&uuml;me yoğunlaşırsanız o b&ouml;l&uuml;mdeki t&uuml;m engelleri takılmadan ge&ccedil;ebilirsiniz.Bu y&uuml;zden yapmanız gereken tek şey oyuna iyi konsantre olarak <a href="http://www.oyunde.com">oyun oyna</a>maktır.</p>\r\n', 5, 'oyun-oynama-ipuclari');
/*!40000 ALTER TABLE `konular` ENABLE KEYS */;


-- Dumping structure for table oyunde.oyunlar
DROP TABLE IF EXISTS `oyunlar`;
CREATE TABLE IF NOT EXISTS `oyunlar` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `adi` varchar(1500) CHARACTER SET latin5 DEFAULT NULL,
  `kategori` varchar(300) DEFAULT NULL,
  `tanitim` varchar(3500) CHARACTER SET latin5 DEFAULT NULL,
  `resim` varchar(1500) CHARACTER SET latin5 DEFAULT NULL,
  `hit` int(11) DEFAULT '0',
  `flash` varchar(1500) CHARACTER SET latin5 DEFAULT NULL,
  `etiket` varchar(3000) CHARACTER SET latin5 DEFAULT NULL,
  `isapi` varchar(1500) CHARACTER SET latin5 NOT NULL,
  `etiketisapi` varchar(1500) CHARACTER SET latin5 NOT NULL,
  `tarih` char(150) DEFAULT NULL,
  `oynama` char(50) DEFAULT NULL,
  `onay` char(2) DEFAULT '1',
  `orj` char(50) DEFAULT NULL,
  `ytarih` char(50) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=315 DEFAULT CHARSET=latin1;

-- Dumping data for table oyunde.oyunlar: ~163 rows (approximately)
DELETE FROM `oyunlar`;
/*!40000 ALTER TABLE `oyunlar` DISABLE KEYS */;
INSERT INTO `oyunlar` (`id`, `adi`, `kategori`, `tanitim`, `resim`, `hit`, `flash`, `etiket`, `isapi`, `etiketisapi`, `tarih`, `oynama`, `onay`, `orj`, `ytarih`) VALUES
	(2, 'Akrobasi Uçagı oyna\r\n', 'aksiyon', 'Akrobasi ucagının klavyenizden yönlendirerek puanlar alabilir yeni akrobatik hareketlerle oyun zevkinize zevk katabilirsiniz', 'akrobasi_ucagi.png', 39, 'akrobasi_ucagi.swf\r\n', 'akrobasi ucağı oyna,ucak oyunu oyna, ucak sürme oyunu oyna,akrobasi ucagı sürme oyunu', 'akrobasi-ucagi-oyna', 'akrobasi-ucagi-oyna,ucak-oyunu-oyna,-ucak-surme-oyunu-oyna,akrobasi-ucagi-surme-oyunu', '03.05.2012 11:28:33', 'klavye', '1', NULL, NULL),
	(3, 'Megamen Oyna', 'Aksiyon', '<p>\r\n	&Uuml;nl&uuml; atari oyunu olan Megameni &uuml;cretsiz olarak oynayabilir.Megamene bu zorlu yolcugulunda d&uuml;smanlarina karsi megamene&#39; yardimci olabilirsiniz.Megamene oyununda ilerledikce yeni gelismis silahlarla canavarlara karsi daha fazla puan kazanin</p>\r\n', 'megamen-oyna.jpg', 73, 'megamen-oyna.swf', 'megaman oyunu oyna,ücretsiz megamen oyna,indirmeden megamen oyna,direk megamen oyna,megamen flash oyna', 'megamen-oyna', 'megaman-oyunu-oyna,ucretsiz-megamen-oyna,indirmeden-megamen-oyna,direk-megamen-oyna,megamen-flash-oyna', '03.05.2012 12:28:33', 'klavye', '1', NULL, NULL),
	(4, 'Uzaylı Avı', 'Aksiyon', 'Uzay aracınızı kontrol ederek uzaylıları avlayabilrisiniz.Level atladdıkça gelişen geminiz ile daha çok uzaylı avlayın her uzaylıda daha çok puan elde edin.  Uzay aracınızın kontrolünü maouse ile yapılmaktadır.', 'uzayli-avi.jpg', 32, 'uzayli-avi.swf', 'Uzaylı avı oyna, ücretsiz uzaylı avı,uzay yolu oyunu,indirmeden uzaylı avı oyunu oyna,uzay oyunu', 'uzayli-avi', 'uzayli-avi-oyna,-ucretsiz-uzayli-avi,uzay-yolu-oyunu,indirmeden-uzayli-avi-oyunu-oyna,uzay-oyunu', '03.05.2012 13:28:33', 'mouse', '1', NULL, NULL),
	(5, 'Son Savunma Merkezi', 'Strateji', '  Son savunma ile merkezinizi mutant canavarlara karşı savunuyorsunuz.Oyun içersinde ilerleyen levellerde güclenen canavarlara karşı silahlarınızda güclenmektedir.Her levelde biraz  daha artan eglence ile oyuna bagımlılıgınız biraz daha artmaktadır.Son savunma mause ile oynanmaktadır.', 'son-savunma-merkezi.jpg', 55, 'son-savunma-merkezi.swf', 'savunma oyunu,son savunma indir,yaratık oyunu oyna,strateji oyunu oyna,savunma strateji oyunu', 'son-savunma-merkezi', 'savunma-oyunu,son-savunma-indir,yaratik-oyunu-oyna,strateji-oyunu-oyna,savunma-strateji-oyunu', '03.05.2012 14:28:33', 'klavye', '1', NULL, NULL),
	(6, 'Kamyon Sür', 'araba', 'Ücretsiz olarak dev bir kamyonu dagda sürebilir ve çeşitli bölümlerde çeşitli arazilerde aracınızı zorlu yollarda sürebilirsiniz.Ücretsiz olarak dev tekerlikli kamyonunuzla eğlenceyi yaşayın', 'kamyon-sur.jpg', 44, 'kamyon-sur.swf', 'kamyon sürme oyunu,kamyon sür,indirmeden kamyon sürme oyunu oyna,ücretsiz kamyon sür,dagda kamyon sür', 'kamyon-sur', 'kamyon-surme-oyunu,kamyon-sur,indirmeden-kamyon-surme-oyunu-oyna,ucretsiz-kamyon-sur,dagda-kamyon-sur', '03.05.2012 15:28:33', 'klavye', '1', NULL, NULL),
	(7, 'Araba modif et', 'araba', 'Ücretsiz olarak istediğiniz arabayı modif edin ve geliştirin.Arabanızın arkaplanını rengini jantlarına kadar herşeyi değiştirip geliştirebilirsiniz', 'araba-modif-et.jpg', 311, 'araba-modif-et.swf', 'araba modif et, araba geliştir,ücretsiz araba boya,araba modifikasyonu,internetten araba modif et,araba gelişimi', 'araba-modif-et', 'araba-modif-et,-araba-gelistir,ucretsiz-araba-boya,araba-modifikasyonu,internetten-araba-modif-et,araba-gelisimi', '03.05.2012 16:28:33', 'klavye', '1', NULL, NULL),
	(8, 'Balık Avla', 'Diger', 'Balık avlamak istermiydiniz? Cevabınız evet ise bu oyun tam size göre oyunda "space" boşluk tuşuna basarak balık avlayabilirsiniz', 'balik-avla.jpg', 47, 'balik-avla.swf', 'İnternetten balık avla,balık avlama oyunu oyna,flash balık avla,indirmeden balık oyunu,balık oyunu indir', 'balik-avla', 'internetten-balik-avla,balik-avlama-oyunu-oyna,flash-balik-avla,indirmeden-balik-oyunu,balik-oyunu-indir', '03.05.2012 17:28:33', 'klavye', '1', NULL, NULL),
	(9, 'Poker Oyna', 'Strateji', 'Ücretsiz olarak internet üzerinden ünlü kağıt oyunu olan poker oynayabilirsiniz tamamiyle yasal :) Bilgisayarınıza indirmeden poker oynama zevkini yaşayın', 'poker-oyna.jpg', 82, 'poker-oyna.swf', 'Poker oyna,ücretsiz poker oyna,yasal poker oyna,flash poker oyna,zevkine poker, indirmeden poker oyna,parasız poker oyner,poker', 'poker-oyna', 'poker-oyna,ucretsiz-poker-oyna,yasal-poker-oyna,flash-poker-oyna,zevkine-poker,-indirmeden-poker-oyna,parasiz-poker-oyner,poker', '03.05.2012 18:28:33', 'klavye', '1', NULL, NULL),
	(11, 'Büyük dövüş', 'ikikisilik', 'İnternet üzerinden karşılıklı olarak arkadaşlarınızla dövüş oyunu oynayabilirsiniz.Üstelik indirmeden tek ekrandan karşılıklı dövüş oyunu oynamanın keyfine varın.', 'buyuk-dovus.jpg', 30, 'buyuk-dovus.swf', ' iki kişik dövüş oyunu,iki kişilik oyunu,dövüş oyunu,karşılıklı dövüş oyunu,internetten karşılıklı dövüş oyunu', 'buyuk-dovus', '-iki-kisik-dovus-oyunu,iki-kisilik-oyunu,dovus-oyunu,karsilikli-dovus-oyunu,internetten-karsilikli-dovus-oyunu', '04.05.2012 18:21:56', 'klavye', '1', NULL, NULL),
	(12, 'Uçan tavşan', 'Macera', '    Uçan süper tavşan yönlendirmeniz için sizden emin bekliyor,Bombaları toplayarak bölümü bitirmesini yardımcı olun.Bombaları toplayarak uçan biyonik tavşana yolunu gösterim hemde eğlencenin dibine vurun', 'ucan-tavsan.jpg', 28, 'ucan-tavsan.swf', 'Uçan tavşan oyna,tavşan oyunu oyna,bug bunny oyna,biyonik tavşan oyunu oyna ,tavşanlar , flash tavşan oyunu,avcı tavşan oyunu oyna', 'ucan-tavsan', 'ucan-tavsan-oyna,tavsan-oyunu-oyna,bug-bunny-oyna,biyonik-tavsan-oyunu-oyna-,tavsanlar-,-flash-tavsan-oyunu,avci-tavsan-oyunu-oyna', '04.05.2012 18:27:02', 'klavye', '1', NULL, NULL),
	(14, 'Half Life oyna', 'Silah', ' Sierranın efsanevi oyunu olan half life ücretsiz olarak oynayabilirsiniz.Düşmanlarınız olan zombi ve askerlere karşı bu mücadelede gordon freemana yardım edin , half life ile sınırsız eğlenceye varın', 'half-life-oyna.jpg', 147, 'half-life-oyna.swf', 'half life oyna , indirmeden half life oyna,hay life oyna,flash half life onya , ücretsiz half life oyna, direk half life oyna', 'half-life-oyna', 'half-life-oyna-,-indirmeden-half-life-oyna,hay-life-oyna,flash-half-life-onya-,-ucretsiz-half-life-oyna,-direk-half-life-oyna', '05.05.2012 18:17:43', 'mouse', '1', NULL, NULL),
	(15, 'Tetikçi oyna', 'Aksiyon', 'Ünlü bir tetikçi olmak istermiydiniz? cevabınız evetse bu oyun tam size göre kontrol ettiginiz karakteri görünmez yapıp düşmanlarını yenmesinde yardımcı olun.Tetikciniz kontrol etmeniz için sizin bekliyor', 'tetikci-oyna.jpg', 78, 'tetikci-oyna.swf', 'tetikçi oyna,ücretsiz assassion oynai,adam öldürme oyunu,adam avlama oyunu,av oyunu,indirmeden adam avlama,tetikci oyunun,asas oyunu', 'tetikci-oyna', 'tetikci-oyna,ucretsiz-assassion-oynai,adam-oldurme-oyunu,adam-avlama-oyunu,av-oyunu,indirmeden-adam-avlama,tetikci-oyunun,asas-oyunu', '05.05.2012 18:43:15', 'klavye', '1', NULL, NULL),
	(16, 'Zombi Ez', 'Macera', 'Arabanızla zombileri öldürürek para kazanın kazandıgınız paralarla yeni arabalar yeni silahlar yeni savaş araçları satın alın.Zombi ez oyunu ile eğlenceyi yaşayın', 'zombi-ez.jpg', 121, 'zombi-ez.swf', 'zombi ez,arabayla zombi ez,zombi parcala,araba sür,araba modif et,zombi öldür', 'zombi-ez', 'zombi-ez,arabayla-zombi-ez,zombi-parcala,araba-sur,araba-modif-et,zombi-oldur', '06.05.2012 08:49:51', 'klavye', '1', NULL, NULL),
	(17, 'Kareteci Mario', 'Aksiyon', ' Atari oyunlarının olmazsa olmazı olan mario yu bu sefer farklı bir şekilde kontrol ediyoruz çünkü bu sefer mari karete yaparak düşmanları yeniyor.Kareteci mario ile düşmanlarını yenmesinde yardımcı olun.', 'kareteci-mario.jpg', 104, 'kareteci-mario.swf', 'dövüşçü mario,kungfucu maryo,maryo,dövüşen mario,mario oyna,karete yapan mario oyna,kung fu mario,tekvando mario', 'kareteci-mario', 'dovuscu-mario,kungfucu-maryo,maryo,dovusen-mario,mario-oyna,karete-yapan-mario-oyna,kung-fu-mario,tekvando-mario', '06.05.2012 10:52:53', 'klavye', '1', NULL, NULL),
	(18, 'Polis arabası sürün', '3Boyutlu', 'Araba sürmeyi seviyorsanız bu oyun tam size göre çünkü 3 boyutlu olarak polis arabası sürüyorsunuz,şehir içinde polis arabasıyla giderken yoldaki diğer arabalardan kaçmaya çalışıyorsunuz', 'polis-arabasi-surun.jpg', 163, 'polis-arabasi-surun.swf', '3 boyutlu araba sür,3 boyutlu polis arabası sür, polis arabasıyla gez,online polis arabası sürün', 'polis-arabasi-surun', '3-boyutlu-araba-sur,3-boyutlu-polis-arabasi-sur,-polis-arabasiyla-gez,online-polis-arabasi-surun', '06.05.2012 15:16:44', 'klavye', '1', NULL, NULL),
	(19, 'Kale Koruma', 'Strateji', 'Oyunda bellirli leveller boyunca kalenizi savunuyorsunuz her bölüm atladıkca yeni silahlar ile kalenizi geliştiriyorsunuz her gelişmede yeni bir heyecan ve yeni güçlendirmeler eklenmektedir.', 'kale-koruma.jpg', 28, 'kale-koruma.swf', 'kaleni savunma,kaleni savunma,savunma oyunu,kale oyunu oyna,savunma oyunu oyna ,kale savunma strateji oyunu', 'kale-koruma', 'kaleni-savunma,kaleni-savunma,savunma-oyunu,kale-oyunu-oyna,savunma-oyunu-oyna-,kale-savunma-strateji-oyunu', '06.05.2012 21:05:01', 'klavye', '1', NULL, NULL),
	(20, 'Taksi Sür', 'yaris', '    Taksi sürmek istermiydiniz ? cevabınız evet ise bu oyun tam size göre taksinizle çeşitli görevleri yaparak puanlar toplayabilirsiniz', 'taksi-sur.jpg', 71, 'taksi-sur.swf', 'taksi sür,internetten taksi sür,indirmeden taksi oyunu oyna,taksi oyunları,taksi,taksi oyun,', 'taksi-sur', 'taksi-sur,internetten-taksi-sur,indirmeden-taksi-oyunu-oyna,taksi-oyunlari,taksi,taksi-oyun,', '08.05.2012 10:55:03', 'klavye', '1', NULL, NULL),
	(21, 'Işıklı Motor Sür', 'yaris', '    Taksi sürmek istermiydiniz ? cevabınız evet ise bu oyun tam size göre taksinizle çeşitli görevleri yaparak puanlar toplayabilirsiniz', 'isikli-motor-sur.jpg', 67, 'isikli-motor-sur.swf', 'Motor sür , ışıklı motorsiklet sür , motor oyunu oyna, indirmeden motor oyun oyna, internetten motorsiklet sür', 'isikli-motor-sur', 'motor-sur-,-isikli-motorsiklet-sur-,-motor-oyunu-oyna,-indirmeden-motor-oyun-oyna,-internetten-motorsiklet-sur', '08.05.2012 10:56:28', 'klavye', '1', NULL, NULL),
	(22, 'Balon patlatma', 'Beceri', ' Balonları patlatarak günün tüm stresini üzerinizden atın , oyunda ipinizle balonları patlatarak puan topluyorsunuz topların size değmeden patlatmanız gerek yoksa oyunda canınız gitmektedir.', 'balon-patlatma.jpg', 303, 'balon-patlatma.swf', 'Balon patlama oyunu oyna , balonları patlat, balon patlatmaca, balon patlamaca oyunları,iple balon patlat', 'balon-patlatma', 'balon-patlama-oyunu-oyna-,-balonlari-patlat,-balon-patlatmaca,-balon-patlamaca-oyunlari,iple-balon-patlat', '08.05.2012 18:18:35', 'klavye', '1', NULL, NULL),
	(23, 'Sonic Oyna', 'Macera', 'Ünlü mavi tilki sonic kontrol etmek istermisiniz? Cevabınız evet ise sonic klavyede parmaklarınızın ucunda yapmanız gereken tek şey ona oyunda yardımcı olmak', 'sonic-oyna.jpg', 84, 'sonic-oyna.swf', 'sonic oyna ücretsiz,flash sonic oyna,indirmeden sonic oyna,internetten sonic oyna,tilki oyunu oyna,mavi tilki oyunu', 'sonic-oyna', 'sonic-oyna-ucretsiz,flash-sonic-oyna,indirmeden-sonic-oyna,internetten-sonic-oyna,tilki-oyunu-oyna,mavi-tilki-oyunu', '09.05.2012 16:05:31', 'klavye', '1', NULL, NULL),
	(24, 'Meb şişe vurmaya oyunu oyna', 'meboyunlari', 'Meb tarafından onaylanmış oyun olan şişe vurmaca oyununu oynarken büyük zevk alıcaksınız .Meb onaylı bu oyunda asıl amaç şişeleri vurarak puan elde etmektir.', 'meb-sise-vurmaya-oyunu-oyna.jpg', 44, 'meb-sise-vurmaya-oyunu-oyna.swf', 'meb şişe vur,meb oyunları,mebin en yeni oyunları,meb tarafından onaylı oyunlar,meb lisanslı oyunlar,meb şişe vurma oyunu oyna ,ücretsiz şişe çevirme oyunu oyna', 'meb-sise-vurmaya-oyunu-oyna', 'meb-sise-vur,meb-oyunlari,mebin-en-yeni-oyunlari,meb-tarafindan-onayli-oyunlar,meb-lisansli-oyunlar,meb-sise-vurma-oyunu-oyna-,ucretsiz-sise-cevirme-oyunu-oyna', '10.05.2012 10:23:01', 'klavye', '1', NULL, NULL),
	(25, 'Bmw meb oyunu', 'meboyunlari', 'Meb tarafından oynaylanmış bir başka oyun olan bmw sürme oyununu sizlere sunuyoruz oyunda bir bmw yi kontrol ediyorsunuz ayrıca sürerken oyun içindeki yoldaki engelleri aşmaya çalışıyoruz. Her bölüm geçtikce yükselen puanınızla beraber yoldaki engellerinizde zorlaşmaktadır.', 'bmw-meb-oyunu.jpg', 129, 'bmw-meb-oyunu.swf', 'bmw oyunu,meb bmw oyunu,bmw sur meb,bmw oyunu oyna,meb bmw oyunu oyna', 'bmw-meb-oyunu', 'bmw-oyunu,meb-bmw-oyunu,bmw-sur-meb,bmw-oyunu-oyna,meb-bmw-oyunu-oyna', '10.05.2012 13:15:23', 'klavye', '1', NULL, NULL),
	(27, 'Uçak Savaşı', 'Aksiyon', 'Eğer bir uçak pilotu olmak istiyorsanız bu oyun tam siz göre pilot koltuguna oturup uzman bir bir pilot olarak uçagınızı sürün ve önünüze gelen engelleri yok edin.', 'ucak-savasi.jpg', 103, 'ucak-savasi.swf', 'Uçak savaşı oyna, uçak uçurma oyunu, uçak savaşlarıi ücretsiz uçak sürme oyunu,uçak şovu oyunu', 'ucak-savasi', 'ucak-savasi-oyna,-ucak-ucurma-oyunu,-ucak-savaslarii-ucretsiz-ucak-surme-oyunu,ucak-sovu-oyunu', '11.05.2012 22:20:47', 'klavye', '1', NULL, NULL),
	(28, 'Serbet Vuruş', 'Spor', 'Eğer sizde futbol seven bir insansanız bu oyun tam size göre eğer şut çekmek pas atmak kaleyi yoklamak istiyorsanız oynamak için tıklayınız.', 'serbet-vurus.jpg', 37, 'serbet-vurus.swf', 'Serbet Vuruş oyna, ücretsiz futbol oyna, Serbet Vuruş indirmeden oyna,futbol oyunu oyna', 'serbet-vurus', 'serbet-vurus-oyna,-ucretsiz-futbol-oyna,-serbet-vurus-indirmeden-oyna,futbol-oyunu-oyna', '12.05.2012 13:04:43', 'klavye', '1', NULL, NULL),
	(29, 'Var mısın Yok musun ', 'Diger', 'Var mısın yok musun oyununu sizde oynayıp zekanızı geliştirin.', 'var-misin-yok-musun-.jpg', 34, 'var-misin-yok-musun-.swf', 'var mısın yok musun, var mısın yok musun oyna, yarışma oyna, var mısın yok musun yarışma oyunu oyna', 'var-misin-yok-musun-', 'var-misin-yok-musun,-var-misin-yok-musun-oyna,-yarisma-oyna,-var-misin-yok-musun-yarisma-oyunu-oyna', '12.05.2012 13:26:10', 'mouse', '1', NULL, NULL),
	(30, 'Penaltı Atışları', 'Spor', 'Penaltı atışı oynayarak keyfinize keyif katınız. Futbol konusunda kendinizi geliştirin.', 'penalti-atislari.jpg', 46, 'penalti-atislari.swf', 'penaltı atışı, penaltı atışı oyna, penaltı, penaltı oyunu', 'penalti-atislari', 'penalti-atisi,-penalti-atisi-oyna,-penalti,-penalti-oyunu', '12.05.2012 13:34:53', 'mouse', '1', NULL, NULL),
	(31, 'Plajda Park Et', 'yaris', 'Plajda park oyunu çok keyifli ve güzel bir oyun dikkat beceriniz bu oyunla daha da çok artacaktır.', 'plajda-park-et.jpg', 29, 'plajda-park-et.swf', 'plajda park, plajda park etme, araba park et, plajda araba park etme oyunu, plajda araba park et oyna', 'plajda-park-et', 'plajda-park,-plajda-park-etme,-araba-park-et,-plajda-araba-park-etme-oyunu,-plajda-araba-park-et-oyna', '12.05.2012 13:46:27', 'klavye', '1', NULL, NULL),
	(32, 'Benzinlikte Park Et', 'yaris', 'Çok dikkat gerektiren bu oyun çok eğlenceli olup oynayan insanların daha da heyecanlandırıyor.', 'benzinlikte-park-et.jpg', 19, 'benzinlikte-park-et.swf', 'benzinlikte park  et, benzinlikte araba park et, benzinlikte park etme oyunu', 'benzinlikte-park-et', 'benzinlikte-park--et,-benzinlikte-araba-park-et,-benzinlikte-park-etme-oyunu', '12.05.2012 13:53:13', 'klavye', '1', NULL, NULL),
	(33, 'Hazine Avcısı 2', 'Beceri', 'Her başardığınız level sonunda işini kolaylaştıracak şeyler satın alabilirsin. Her level toplaman gereken miktar yükseliyor.', 'hazine-avcisi-2.jpg', 78, 'hazine-avcisi-2.swf', 'hazine avcısı, hazine avcısı oyna, hazine avcısı oyunu, hazine oyunu oyna ', 'hazine-avcisi-2', 'hazine-avcisi,-hazine-avcisi-oyna,-hazine-avcisi-oyunu,-hazine-oyunu-oyna-', '12.05.2012 14:08:07', 'mouse', '1', NULL, NULL),
	(34, 'Air Hockey 2', 'Beceri', 'Bu oyunu oynarken zevk alacaksınız. Becerinizi geliştireceğiniz oyun ülkeler arası seçiminizi yaptıktan sonra oyuna geçiniz oyun kazandığınızda oyunun seviyesi daha çok zorlanacaktır.', 'air-hockey-2.jpg', 37, 'air-hockey-2.swf', 'air hockey oyna, buz okeyi oyna, air hockey, bu okeyi', 'air-hockey-2', 'air-hockey-oyna,-buz-okeyi-oyna,-air-hockey,-bu-okeyi', '12.05.2012 14:40:04', 'mouse', '1', NULL, NULL),
	(35, 'Yakar Top Turnuva', 'Beceri', 'Yakar top uygulamasında beceriniz ile daha iyi ve isabetli atışlar yaparak rakiplerinizi yenerek şampiyonluğa yükselebilirsiniz.', 'yakar-top-turnuva.jpg', 18, 'yakar-top-turnuva.swf', 'yakar top oyna, yakar top oyunu oyna, yakar top turnuvası, yakar top oyunu, yakar top', 'yakar-top-turnuva', 'yakar-top-oyna,-yakar-top-oyunu-oyna,-yakar-top-turnuvasi,-yakar-top-oyunu,-yakar-top', '12.05.2012 14:50:58', 'mouse', '1', NULL, NULL),
	(36, 'Fireman ', 'Macera', 'Fireman Bobomba oyunu herkezin ilgisinde olduğu çok iyi bir oyundur. Oyun içerisinde hediyeler kazanılıyor. Ve oyun daha keyifli bir hale geliyor. İyi oyunlar.', 'fireman-.jpg', 35, 'fireman-.swf', 'fireman oyunu oyna, fireman oyna, bomb, bombs, bomba oyunu oyna, bomba oyunları', 'fireman-', 'fireman-oyunu-oyna,-fireman-oyna,-bomb,-bombs,-bomba-oyunu-oyna,-bomba-oyunlari', '12.05.2012 15:03:47', 'klavye', '1', NULL, NULL),
	(37, 'Maya balon patlatma', 'balonpatlatma', 'Güzel bir maya balon patlatma oyunu, oyunda aynı renkteki balonları yanyana getirerek patlatmaya çalışıyorsunuz balonları patlattıkça puanınızı artıyor böylece bir sonraki seviyeye geçiyorsunuz', 'maya-balon-patlatma.jpg', 191, 'maya-balon-patlatma.swf', 'balon patlatma oyunu,balon patlama,inca balon patlamaca,balon patlamaca oyunlari', 'maya-balon-patlatma', 'balon-patlatma-oyunu,balon-patlama,inca-balon-patlamaca,balon-patlamaca-oyunlari', '13.05.2012 19:46:59', 'klavye', '1', NULL, NULL),
	(38, 'Element Balon Patlatma', 'balonpatlatma', 'Balon patlatmayı seviyormusunuz o zaman bu oyun tam size göre oyunları patlattıkça puan alıyorsunuz  her ilerleyen bölümde balon patlama işleri daha zorlaşıcaktır.', 'element-balon-patlatma.jpg', 43, 'element-balon-patlatma.swf', 'Elementlerdeki balon patlat,balonları indir,balonları patlat,balon şişir', 'element-balon-patlatma', 'elementlerdeki-balon-patlat,balonlari-indir,balonlari-patlat,balon-sisir', '13.05.2012 19:53:02', 'klavye', '1', NULL, NULL),
	(39, 'Tavşan boyama oyunu', 'boyama', 'Tavşan boyama oyunu ile bir tavşanı boyuyorsunuz,tavşanı istediğiniz zevklerinize göre boyayın hayal gücünüz ve zevkleriniz ile tavşanı boyayın onu reklendirin.', 'tavsan-boyama-oyunu.jpg', 20, 'tavsan-boyama-oyunu.swf', 'boyama oyunu,tavşan boyama oyunu,tavşan boyama,tavşan boya', 'tavsan-boyama-oyunu', 'boyama-oyunu,tavsan-boyama-oyunu,tavsan-boyama,tavsan-boya', '14.05.2012 17:55:43', 'klavye', '1', NULL, NULL),
	(40, 'Balonları patlatan maymun oyunu', 'balonpatlatma', 'Maymun ile balonları patlatmaya hazırmısınız o zaman bu oyun tam size göre yapmanız gereken tek şey sadece maymunuzla balonları patlamak ve eğlencenin dibine varmak', 'balonlari-patlatan-maymun-oyunu.jpg', 40, 'balonlari-patlatan-maymun-oyunu.swf', 'maymun balon,maymun balon patlat,maynum balon patlamaca oyunu,balon patlatma oyunu', 'balonlari-patlatan-maymun-oyunu', 'maymun-balon,maymun-balon-patlat,maynum-balon-patlamaca-oyunu,balon-patlatma-oyunu', '14.05.2012 21:44:39', 'klavye', '1', NULL, NULL),
	(41, 'Balon patlat', 'balonpatlatma', 'Aynı renkteki balonları patlatarak sırayla puan kazanıyorsunuz her puan kazandıkça bir sonraki seviyeye geciyorsunuz her balon patlattıkca oyun biraz daha hızlanmaktadır.', 'balon-patlat.jpg', 120, 'balon-patlat.swf', 'balon patlama oyna,renkli balon patlat,balon gumlet,balonları patlat', 'balon-patlat', 'balon-patlama-oyna,renkli-balon-patlat,balon-gumlet,balonlari-patlat', '15.05.2012 11:29:02', 'klavye', '1', NULL, NULL),
	(42, 'Uçak Sür', 'aksiyon', 'Eğer sizde uçak sürmeyi seviyorsanız bu oyun tam size göre oyunda pilotu canlandırıyorsunuz ve göreviniz rakip ucakları ve düşmanlarınızı avlamak.Uçagınızı sürerek düşmanlarınızı avlayın', 'ucak-sur.jpg', 21, 'ucak-sur.swf', 'ucak sür,ucakları düsür,ucakları patlat,indirmeden ucak sür,ucak oyunu oyna,ucak avla', 'ucak-sur', 'ucak-sur,ucaklari-dusur,ucaklari-patlat,indirmeden-ucak-sur,ucak-oyunu-oyna,ucak-avla', '15.05.2012 11:37:23', 'klavye', '1', NULL, NULL),
	(44, 'Çağlar boyu son savunma 2', 'Strateji', 'Kalenizi savunurken aynı anda karşı tarafı yenmeyi çalışıyorsunuz çağlar boyun savunma oyununda oyunun bu 2.serisinde daha yeni yaratıklar daha yeni silahlar bulunmaktadır çağlar boyu savunma 2 oyununda', 'caglar-boyu-son-savunma-2.jpg', 57, 'caglar-boyu-son-savunma-2.swf', 'son savunma oyna,çağlar boyun savunma oyna,son savunma 2,çağlar boyu savunma oyna 2,son savunma 2  oyuınu oyna,', 'caglar-boyu-son-savunma-2', 'son-savunma-oyna,caglar-boyun-savunma-oyna,son-savunma-2,caglar-boyu-savunma-oyna-2,son-savunma-2--oyuinu-oyna,', '15.05.2012 14:35:23', 'klavye', '1', NULL, NULL),
	(50, 'Balon patlatma 2', 'balonpatlatma', 'Oyun icersinde aynı renkteki balonları patlatarak puan topluyorsunuz oyunda dikkat etmeniz gereken nokta aynı renkteki balonları yanyana getirmektir.', 'balon-patlatma-2.jpg', 94, 'balon-patlatma-2.swf', 'balon patlat,balonları patlat,balon patlatma oyunu oyna,ücretsiz balon patlama oyunu oyna', 'balon-patlatma-2', 'balon-patlat,balonlari-patlat,balon-patlatma-oyunu-oyna,ucretsiz-balon-patlama-oyunu-oyna', '16.05.2012 12:13:00', 'klavye', '1', NULL, NULL),
	(51, 'Elmas Balon patlatma', 'balonpatlatma', 'Elmas şeklindeki balonları patlatarak puan topluyorsunuz oyunda dikkat etmeniz gereken en büyük nokta aynı renkteki elmasları yan yana getirmeye çalışmaktır.', 'elmas-balon-patlatma.jpg', 266, 'elmas-balon-patlatma.swf', 'elmas patlat,elmas patlatma oyunu oyna ,elmas balon patlama oyunu oyna', 'elmas-balon-patlatma', 'elmas-patlat,elmas-patlatma-oyunu-oyna-,elmas-balon-patlama-oyunu-oyna', '16.05.2012 12:18:15', 'klavye', '1', NULL, NULL),
	(52, 'Zuma zum oyunu', 'balonpatlatma', 'Eğer sizde renkli zuma zuma zum oyunlarını seviyorsanız bu oyun çok hoşuna gidicektir.Çünkü oyunda aynı renkte zuma yan yana getirerek  sonuca varmaya çalışıyorsunuz', 'zuma-zum-oyunu.jpg', 221, 'zuma-zum-oyunu.swf', 'zuma zuma zum oyunu oyna ,zuma zum oyunları,ücretsiz zuma zuma zum oyunu oyna', 'zuma-zum-oyunu', 'zuma-zuma-zum-oyunu-oyna-,zuma-zum-oyunlari,ucretsiz-zuma-zuma-zum-oyunu-oyna', '16.05.2012 12:21:12', 'klavye', '1', NULL, NULL),
	(54, 'Yangın Söndür', 'araba', 'Sizde şehir içinde yanan evleri ve işletmeleri kurtarmak için bu oyunu oynayın. Oyun çok gelişmiş düzeydir.', 'yangin-sondur.jpg', 48, 'yangin-sondur.swf', 'yangın söndürücüler, yangın söndür, yangın söndürücüler, tır, yangın, söndürücü, yangın söndürücü oyunu oyna', 'yangin-sondur', 'yangin-sonduruculer,-yangin-sondur,-yangin-sonduruculer,-tir,-yangin,-sondurucu,-yangin-sondurucu-oyunu-oyna', '17.05.2012 21:30:07', 'klavye', '1', NULL, NULL),
	(55, 'Park Etme Yeteneği', 'araba', 'Sizde bu oyunu oynayarak yeteneğinize yetenek katın. Çok dikkat gerektiren bu oyun eğlenceli ve çok zevklidir.', 'park-etme-yetenegi.jpg', 43, 'park-etme-yetenegi.swf', 'park etme yetenek, park etme yeteneği, park ederken yetenek kazanma, park edilirken yetenek kazanın', 'park-etme-yetenegi', 'park-etme-yetenek,-park-etme-yetenegi,-park-ederken-yetenek-kazanma,-park-edilirken-yetenek-kazanin', '17.05.2012 21:37:48', 'klavye', '1', NULL, NULL),
	(56, 'Barbie alışveriş yapıyor', 'kiz', 'Eğer sizde barbie oyunlarını seven biriyseniz barbie alışverişte oyunu tam size göre oyunda barbie giydirip alışverişe götürüyorsunuz', 'barbie-alisveris-yapiyor.jpg', 193, 'barbie-alisveris-yapiyor.swf', 'barbie alışverişte oyunu,barbie alışveriş yapıyorum oyna, barbie oyunu,barbie,barbie giydirme oyunu', 'barbie-alisveris-yapiyor', 'barbie-alisveriste-oyunu,barbie-alisveris-yapiyorum-oyna,-barbie-oyunu,barbie,barbie-giydirme-oyunu', '23.05.2012 10:11:36', 'klavye', '1', NULL, NULL),
	(57, 'Gelinlik giydir', 'kiz', 'Gelinlik giydirme oyunu ile istediğiniz karaktere gelinlik giydirebilir çeşitli takı yüzüklerle gelini süsleyebilirsiniz tek yapmanız gereken  gelinliği giydirmek', 'gelinlik-giydir.jpg', 30, 'gelinlik-giydir.swf', 'gelinlik giydirme oyunları,gelinlik giydirme oyunları oyna,gelinlik oyunları,barbie gelinlik oyunları,', 'gelinlik-giydir', 'gelinlik-giydirme-oyunlari,gelinlik-giydirme-oyunlari-oyna,gelinlik-oyunlari,barbie-gelinlik-oyunlari,', '23.05.2012 10:13:43', 'klavye', '1', NULL, NULL),
	(58, 'Balon patlatma havuzu', 'balonpatlatma', 'Balon patlatmadan buyuk zevk alıyorsanız bu oyun sizler için tek yapmanız gereken havuzdaki balonları patlatmak ve puan toplamak', 'balon-patlatma-havuzu.jpg', 59, 'balon-patlatma-havuzu.swf', 'balon patlama oyunu,havuzdan balon patlama oyna,havuz balonları patlat,havuz patlamaca oyunu', 'balon-patlatma-havuzu', 'balon-patlama-oyunu,havuzdan-balon-patlama-oyna,havuz-balonlari-patlat,havuz-patlamaca-oyunu', '26.05.2012 22:22:48', 'klavye', '1', NULL, NULL),
	(59, 'Adada balon patlatma oyunu', 'balonpatlatma', 'Ada üzerindeki tüm balonları patlamak istermisiniz o zaman adada balon patlama oyunu tam size göre ada üzerindeki balonları patlattıkça ek puan alıyorsunuz', 'adada-balon-patlatma-oyunu.jpg', 55, 'adada-balon-patlatma-oyunu.swf', 'adada balon patlama oyunu oyna,ada balon oyunu,ada balonları patlat oyunu', 'adada-balon-patlatma-oyunu', 'adada-balon-patlama-oyunu-oyna,ada-balon-oyunu,ada-balonlari-patlat-oyunu', '26.05.2012 22:27:52', 'klavye', '1', NULL, NULL),
	(60, 'Maymun balon patlatma 1-2-3', 'balonpatlatma', 'Bir maymunla balonları patlamak istermiydinizi o zaman bu oyunu mutlaka denemelisiniz çünkü bir maymun ile balon patlamak emin olun cok zevkli tek yapmanız gereken mousunuz ile maymunu yöneterek aynı renkteki balonları patlatmak', 'maymun-balon-patlatma-1-2-3.jpg', 51, 'maymun-balon-patlatma-1-2-3.swf', 'maymun balon oyunu,maymun balon patlatıcısı,maymun balon patlama oyunu oyna', 'maymun-balon-patlatma-1-2-3', 'maymun-balon-oyunu,maymun-balon-patlaticisi,maymun-balon-patlama-oyunu-oyna', '26.05.2012 22:36:57', 'mouse', '1', NULL, NULL),
	(61, 'Ben ten (10) balon patlatma', 'boyama', 'Ben 10 ten balon patlatma oyununda ben 10 yardım ederek balonları patlatıyoruz.Oyunda ben 10 düşmanlarına karşı balonları patlatarak üstünlük kazanmasını saglıyoruz.Ben 10 balon patlatma oyununda yardım edin', 'ben-ten-(10)-balon-patlatma.jpg', 17, 'ben-ten-(10)-balon-patlatma.swf', 'ben 10 balon patlatma oyunu, ben 10 balon patlama oyunu oyna,ben 10 oyunları oyna,ben 10 oyna', 'ben-ten-(10)-balon-patlatma', 'ben-10-balon-patlatma-oyunu,-ben-10-balon-patlama-oyunu-oyna,ben-10-oyunlari-oyna,ben-10-oyna', '28.05.2012 17:24:57', 'klavye', '1', NULL, NULL),
	(62, 'Zuma balon patlatma', 'balonpatlatma', 'Oyunda aynı renkteki topları vurarak puan topluyorsunuz yapmanız gereken tek şey maouse ile aynı renkteki topları vurarak puan toplamaktır.', 'zuma-balon-patlatma.jpg', 92, 'zuma-balon-patlatma.swf', 'zuma zuma balon oyunu,zuma zuma zum balon patlatma oyna,zum balon patlatma', 'zuma-balon-patlatma', 'zuma-zuma-balon-oyunu,zuma-zuma-zum-balon-patlatma-oyna,zum-balon-patlatma', '29.05.2012 22:07:55', 'mouse', '1', NULL, NULL),
	(63, 'Zuma 2 balon patlat', 'balonpatlatma', 'Oyunda mousenin ile aynı renkteki topları yan yana getirere puan topluyorsunuz böylece bir sonraki lvlde daha hızlı bir şekilde balon patlatmaya çalışıyorsunuz', 'zuma-2-balon-patlat.jpg', 46, 'zuma-2-balon-patlat.swf', 'zuma 2 delux balon patlatma,zum 2 balon patlatma oyna', 'zuma-2-balon-patlat', 'zuma-2-delux-balon-patlatma,zum-2-balon-patlatma-oyna', '29.05.2012 22:10:11', 'mouse', '1', NULL, NULL),
	(64, 'Kayak Oyunu', 'macera', 'Bu oyun macera dolu olup oynayana zevkli ve keyfili bir ortam yaratır.', 'kayak-oyunu.jpg', 15, 'kayak-oyunu.swf', 'kayak, kayak oyunu, kayak oyna, kayma, kayma oyunu', 'kayak-oyunu', 'kayak,-kayak-oyunu,-kayak-oyna,-kayma,-kayma-oyunu', '31.05.2012 16:38:02', 'klavye', '1', NULL, NULL),
	(65, 'Karete', 'aksiyon', 'Karete oyununda aksiyon dolu maceralı saatler sizleri bekliyor.', 'karete.jpg', 29, 'karete.swf', 'karete oyunu, karete, karete oyna, karate oyunu oyna', 'karete', 'karete-oyunu,-karete,-karete-oyna,-karate-oyunu-oyna', '31.05.2012 16:46:23', 'klavye', '1', NULL, NULL),
	(67, 'Buz Okeyi', 'macera', 'Buz okeyi oyunu dikkat gerektiren oyundur. Dikkatli ve temkinli oynanması gerekilen bu oyunla oynadıkça skorunuzu yukseltecek hızlı olamanız gerekir', 'buz-okeyi.jpg', 26, 'buz-okeyi.swf', 'buz okeyi, buz okeyi oyunu, buz okeyi oyunu oyna, buz, okey', 'buz-okeyi', 'buz-okeyi,-buz-okeyi-oyunu,-buz-okeyi-oyunu-oyna,-buz,-okey', '31.05.2012 16:54:00', 'klavye', '1', NULL, NULL),
	(68, 'Golf Oyna', 'Beceri', 'Golf oyunu ile becerinizi arttırın. Ve dikkatli olarak oyunu başarı ile tamamlayınız.', 'golf-oyna.jpg', 15, 'golf-oyna.swf', 'golf oyunu, golf oyna, golf, golf oyunu oyna', 'golf-oyna', 'golf-oyunu,-golf-oyna,-golf,-golf-oyunu-oyna', '31.05.2012 16:55:04', 'mouse', '1', NULL, NULL),
	(69, 'Bowling Oyna', 'macera', 'Bowling oyunu keyif li olmakla birlikte oynayan tarafından dikkatli olunması gerektiren bu oyun, oynayana keyifli oyunlar dileriz..', 'bowling-oyna.jpg', 47, 'bowling-oyna.swf', 'bowling, bowling oyna, bowling oyunu oyna, bowling oyunu', 'bowling-oyna', 'bowling,-bowling-oyna,-bowling-oyunu-oyna,-bowling-oyunu', '31.05.2012 17:02:52', 'mouse', '1', NULL, NULL),
	(70, 'Tank savaşı oyna', 'Strateji', 'Tank savaşlarını seven biriyseniz bu oyun tam size göre çünkü tank savaşlarında herşey tam sizin istediğiniz gibi oyun seçenekleri ve menüleri tam size göre sadece oyuna girmek ve tankınızı yönetmek', 'tank-savasi-oyna.jpg', 19, 'tank-savasi-oyna.swf', 'tank savaşları,tank savaşı oyna,ücretsiz tank savaşı,tank savaştırma', 'tank-savasi-oyna', 'tank-savaslari,tank-savasi-oyna,ucretsiz-tank-savasi,tank-savastirma', '06.06.2012 16:01:11', 'klavye', '1', NULL, NULL),
	(71, 'Smarty Kabarcıklar', 'balonpatlatma', 'Aynı renklerdeki balonları arka arkaya dizili bir şekilde sıraladıktan sonra balonlar patlatılır. 3 balon arka arkaya geldiğinde ise balonlar patlamaya başlar.', 'smarty-kabarciklar.jpg', 83, 'smarty-kabarciklar.swf', 'balon oyunu oyna, balon oyna, balon diz, balon sıkıştır', 'smarty-kabarciklar', 'balon-oyunu-oyna,-balon-oyna,-balon-diz,-balon-sikistir', '07.06.2012 11:47:38', 'mouse', '1', NULL, NULL),
	(72, 'Balon Meydanı', 'balonpatlatma', 'Balonları patlatmak için sağ kısımdaki iğne, çubuk gibi materyalleri kullanarak balonları patlatınız.', 'balon-meydani.jpg', 49, 'balon-meydani.swf', 'balon oyunu oyna, balon oyna, balonları iğne ile patlat', 'balon-meydani', 'balon-oyunu-oyna,-balon-oyna,-balonlari-igne-ile-patlat', '07.06.2012 11:53:11', 'mouse', '1', NULL, NULL),
	(73, 'Balona İsabet', 'balonpatlatma', 'Balonlara nişan alarak patlatıyoruz. İsabetli atışlar yaparak balonları patlaması durumunda seviyenizi ilerletebilirsiniz.', 'balona-isabet.jpg', 17, 'balona-isabet.swf', 'balona isabet, balona isabet ederek patlatma, balonları patlat, isabet, isabetli balon patlat', 'balona-isabet', 'balona-isabet,-balona-isabet-ederek-patlatma,-balonlari-patlat,-isabet,-isabetli-balon-patlat', '07.06.2012 11:57:36', 'mouse', '1', NULL, NULL),
	(74, 'Ameliyat Oyunu', 'Beceri', 'Hasta olan kişileri ameliyatlarını siz gerçekleştirin ve deneyim kazanın. Böylelikle vücudumuzu örneklerle incelemiş ve vücudumuzun yapısını öğrenebilirsiniz.', 'ameliyat-oyunu.jpg', 48, 'ameliyat-oyunu.swf', 'ameliyat, ameliyat yapma, hasta, hastayı ameliyat etme', 'ameliyat-oyunu', 'ameliyat,-ameliyat-yapma,-hasta,-hastayi-ameliyat-etme', '15.06.2012 14:28:18', 'mouse', '1', NULL, NULL),
	(75, 'Tanker Taşı', 'Beceri', 'Sizde tanker dolu eşyalarınızı deniz yolu aracılığıyla taşıyın rahat edin. Trafik derdi olmadan eşya ulaşımını kolaylaştırınız.', 'tanker-tasi.jpg', 20, 'tanker-tasi.swf', 'tanker, tanker taşı, tanker taşıma, tanker taşımacılığı, denizde tanker taşı', 'tanker-tasi', 'tanker,-tanker-tasi,-tanker-tasima,-tanker-tasimaciligi,-denizde-tanker-tasi', '15.06.2012 17:05:47', 'mouse', '1', NULL, NULL),
	(76, 'Bilardo Oyna', 'Spor', 'Bilardo izlemesi keyif olan bir spordur. Bu keyifli oyunu bizimle beraber oynamaya ne dersiniz. Hadi başlayalım', 'bilardo-oyna.jpg', 23, 'bilardo-oyna.swf', 'bilardo oyna, bilardo oyunu oyna, bilardo, bilardo nasıl oynanır', 'bilardo-oyna', 'bilardo-oyna,-bilardo-oyunu-oyna,-bilardo,-bilardo-nasil-oynanir', '15.06.2012 17:13:39', 'mouse', '1', NULL, NULL),
	(77, 'Drag Yarışı', 'yaris', 'Sizde topraklı yollarda aracınız kaydırarak adrenalin elde etmek istiyorsanız bu oyunu oynayabilirsiniz.', 'drag-yarisi.jpg', 47, 'drag-yarisi.swf', 'drag, drag yarışı, drag yarışı oyna, yarış oyna drag oyunu, drag oyunu oyna', 'drag-yarisi', 'drag,-drag-yarisi,-drag-yarisi-oyna,-yaris-oyna-drag-oyunu,-drag-oyunu-oyna', '15.06.2012 17:20:09', 'klavye', '1', NULL, NULL),
	(78, 'Bmw Z8 Puzzle', 'Puzzle', 'Sizin de hayalinizde ki araba markalarından biri olan BMW aracı puzzle parçalarını birleştirerek birbirleri ile birleştirerek aracı görünülür hale getirin..', 'bmw-z8-puzzle.jpg', 10, 'bmw-z8-puzzle.swf', 'puzzle, puzzle tamamlama, puzzle yap, puzzle oyunu, araba puzzle', 'bmw-z8-puzzle', 'puzzle,-puzzle-tamamlama,-puzzle-yap,-puzzle-oyunu,-araba-puzzle', '15.06.2012 17:28:57', 'mouse', '1', NULL, NULL),
	(79, 'Var Mısın Yok Musun', 'Beceri', 'Sizde var mısın yok musun oynayarak beceriniz geliştiriniz. Heyecan dolu bu yarışmaya var mısınız yok musunuz.', 'var-misin-yok-musun.jpg', 11, 'var-misin-yok-musun.swf', 'var mısın yok musun, var mısın, yok musun, var mısın oyna, yok musun var mısın oyunu', 'var-misin-yok-musun', 'var-misin-yok-musun,-var-misin,-yok-musun,-var-misin-oyna,-yok-musun-var-misin-oyunu', '16.06.2012 15:25:44', 'mouse', '1', NULL, NULL),
	(80, 'Bilardo', 'Spor', 'Bilardo oyunu çok zevkli ve heyecan dolu bir oyundur. Sizde bu oyunu oynamak isterseniz oyna butonuna basmanız yeterlidir.\r\n', 'bilardo.jpg', 17, 'bilardo.swf', 'bilardo oyna, bilardo oyunu oyna, bilardo, bilardo nasıl oynanır', 'bilardo', 'bilardo-oyna,-bilardo-oyunu-oyna,-bilardo,-bilardo-nasil-oynanir', '16.06.2012 16:17:43', 'mouse', '1', NULL, NULL),
	(81, 'Yerçekimi Çocuğu', 'macera', 'Yer çekimi çocuğu ve iki ile büyük maceraya hazırmısınız. Macera dolu bu oyun, için oyunu başlat butonuna basmanız yeterli..', 'yercekimi-cocugu.jpg', 20, 'yercekimi-cocugu.swf', 'Yer Çekim, Yerçekimi Çocuğu, Yer Çekimi Oyunu, Yer Çekimi çoçuğu oyunu oyna', 'yercekimi-cocugu', 'yer-cekim,-yercekimi-cocugu,-yer-cekimi-oyunu,-yer-cekimi-cocugu-oyunu-oyna', '26.07.2012 12:17:25', 'klavye', '1', NULL, NULL),
	(82, 'Cesur Çocuk', 'macera', 'Kötü adamlar tarafından kaçırılan kızı motoruyla onun peşine düşen cesur çocuk kurtaracaktır. Sizde cesur çocuğun yerine geçin ve kızı siz kurtarın.', 'cesur-cocuk.jpg', 14, 'cesur-cocuk.swf', 'Cesur Çocuk, Macera Oyunu, Kız Kurtarma, Kurtarma Oyunu, Oyun Oyan', 'cesur-cocuk', 'cesur-cocuk,-macera-oyunu,-kiz-kurtarma,-kurtarma-oyunu,-oyun-oyan', '26.07.2012 12:22:15', 'klavye', '1', NULL, NULL),
	(83, 'Ejderha Oyunu', 'macera', 'Macera yolunda ilerleyen çocuğun karşısına çıkan Ejdarha çocuğun altınını alıp çocuğu mahrum bırakmak ister sizde bu çocuğun yerine kendinizi koyun ve maceram yolunda Ejderhadan kaçın', 'ejderha-oyunu.jpg', 14, 'ejderha-oyunu.swf', 'Ejdarha, Macera oyunu, Ejdarhalı Macera oyunu, Kaçış, Altın oyunu, Yakalanma Oyunu', 'ejderha-oyunu', 'ejdarha,-macera-oyunu,-ejdarhali-macera-oyunu,-kacis,-altin-oyunu,-yakalanma-oyunu', '26.07.2012 12:25:51', 'klavye', '1', NULL, NULL),
	(84, 'Mutant Savaşları', 'aksiyon', 'Oyunda mutantları öldürerek puanları topluyorsunuz her puan topladıkça levelini yükseliyor ve yükselen levelinizle beraber daha güçlü silahlar satın alıyorsunuz', 'mutant-savaslari.jpg', 10, 'mutant-savaslari.swf', 'mutant savaşları,aksiyon,mutant oyunları,mutant öldürme oyunu oyna', 'mutant-savaslari', 'mutant-savaslari,aksiyon,mutant-oyunlari,mutant-oldurme-oyunu-oyna', '28.07.2012 08:39:42', 'klavye', '1', NULL, NULL),
	(86, 'Hero 108 Oyna', 'macera', 'Oyunda yönettiğiniz uzaylıyı gemisini kontrol ederek puan topluyorsunuz ve savaş geminizi elde ettiğiniz puanlarla geliştiriyorsunuz.Tek yapmanız gereken olabildigince düşman vurarak puan toplamak', 'hero-108-oyna.jpg', 28, 'hero-108-oyna.swf', 'hero 108,hiro 108 oyna,hero 108 oyunu oyna,108 oyunu', 'hero-108-oyna', 'hero-108,hiro-108-oyna,hero-108-oyunu-oyna,108-oyunu', '28.07.2012 08:42:42', 'klavye', '1', NULL, NULL),
	(87, 'Ülke Savunma', 'Strateji', 'Ülkeni savunma oyunuda  harita üzerinden belli bir adresi düşmanlarınıza karşı savunarak haritanızı ve savunma silahlarınızı geliştirerek puan topluyorsunuz', 'ulke-savunma.jpg', 21, 'ulke-savunma.swf', 'savunma oyunu,ülkeni savun oyunu oyna,savunma merkezi oyunu', 'ulke-savunma', 'savunma-oyunu,ulkeni-savun-oyunu-oyna,savunma-merkezi-oyunu', '28.07.2012 08:55:31', 'klavye', '1', NULL, NULL),
	(88, 'Robotlar Zombilere Karşı', 'Strateji', 'Robot zombi savaşı oyununda robotları kontrol ederek zombilere karşı savaşıyorsunuz böylece zombilerin bölgenize girmenizi engelliyorsunuz.', 'robotlar-zombilere-karsi.jpg', 39, 'robotlar-zombilere-karsi.swf', 'Robot zombi savaşı,robot vs zombi,robot zombi kavgası oyunu', 'robotlar-zombilere-karsi', 'robot-zombi-savasi,robot-vs-zombi,robot-zombi-kavgasi-oyunu', '28.07.2012 08:57:14', 'mouse', '1', NULL, NULL),
	(89, 'Tekila Zombi Avı', 'macera', 'Zombiler tekrar uyandu ve onlar çok açtır. Zombileri avlayarak şehri ve tüm insalığı kurtarmak senin elinde silahını kap ve zombileri avla', 'tekila-zombi-avi.jpg', 37, 'tekila-zombi-avi.swf', 'zombi avı,zombi öldür,tekila içme oyunu,tekila zombi avla,tekila zombi avcısı', 'tekila-zombi-avi', 'zombi-avi,zombi-oldur,tekila-icme-oyunu,tekila-zombi-avla,tekila-zombi-avcisi', '29.07.2012 07:50:58', 'mouse', '1', NULL, NULL),
	(90, 'Çılgın zombiler şehirde', 'macera', 'Bu zombiler yılda bir kez dışarı çıkarlar ve dışardada moda defilesi gibi giyinip kuşanırlar işte bu zombilere puan vermeye ve macera yaşamaya hazırmısın o zaman hemen oynayama başla', 'cilgin-zombiler-sehirde.jpg', 9, 'cilgin-zombiler-sehirde.swf', 'Zombi giydir,zombi macerası,zombi puanla,zombi oyunları,zombi eğlencesi', 'cilgin-zombiler-sehirde', 'zombi-giydir,zombi-macerasi,zombi-puanla,zombi-oyunlari,zombi-eglencesi', '29.07.2012 07:55:51', 'mouse', '1', NULL, NULL),
	(91, 'Zombiler bitkilere karşı', 'macera', 'Zombiler eviniz saldırıp beyninizi yemek istiyor ama bahçenizdeki savaşcı bitkiler buna izin vermicek :) bahçenizde savaşcı zombiler yetiştirerek zombilere karşı kendinizi savunun.', 'zombiler-bitkilere-karsi.jpg', 397, 'zombiler-bitkilere-karsi.swf', 'zombi vs bitki,zombi bitki savaşı,zombi öldürme oyunu,zombi bitki avcısı,bitkilerle zombi avla', 'zombiler-bitkilere-karsi', 'zombi-vs-bitki,zombi-bitki-savasi,zombi-oldurme-oyunu,zombi-bitki-avcisi,bitkilerle-zombi-avla', '29.07.2012 08:06:42', 'mouse', '1', NULL, NULL),
	(92, 'Scooby doo macerası', 'boyama', 'Scooby doo görev başında yeni maceraları ve yeni gizemleri çözmek için uğraşıyor ona bu gizemleri çözmede yardımcı olun', 'scooby-doo-macerasi.jpg', 38, 'scooby-doo-macerasi.swf', 'Scooby doo işbaşında,Scooby doo oyunu oyna,Scooby doo görevleri,Scooby doo gizem çözme oyunu', 'scooby-doo-macerasi', 'scooby-doo-isbasinda,scooby-doo-oyunu-oyna,scooby-doo-gorevleri,scooby-doo-gizem-cozme-oyunu', '29.07.2012 08:12:00', 'klavye', '1', NULL, NULL),
	(93, 'Kanyon Yarışı', 'araba', 'Kanyonda ralli yapmak istiyorsanız bu oyun tam size göre tek yapmanız gereken kanyonda arabanıza atlamak ve ralliye katılmak', 'kanyon-yarisi.jpg', 22, 'kanyon-yarisi.swf', 'kanyon yarışı oyunu oyna,kanyonda araba sürme,kanyon rallisi oyunu,ralli oyunu,ralli yarışı oyunu', 'kanyon-yarisi', 'kanyon-yarisi-oyunu-oyna,kanyonda-araba-surme,kanyon-rallisi-oyunu,ralli-oyunu,ralli-yarisi-oyunu', '30.07.2012 14:20:38', 'klavye', '1', NULL, NULL),
	(94, 'Drag yarışları oyunu', 'araba', 'Eğer sizde drağ yarışlarına katılmak istiyorsanız bu oyun tam size göre tek yapmanız gereken arabanızla sokak yarışlarına katılmak', 'drag-yarislari-oyunu.jpg', 6, 'drag-yarislari-oyunu.swf', 'drag yarışı yap,araba,araba sürme oyunu,hızlı araba sür,drağ yarışlarına katılma oyunu,drag yarışı oyna', 'drag-yarislari-oyunu', 'drag-yarisi-yap,araba,araba-surme-oyunu,hizli-araba-sur,drag-yarislarina-katilma-oyunu,drag-yarisi-oyna', '30.07.2012 14:21:55', 'klavye', '1', NULL, NULL),
	(96, 'Drift yarışları', 'araba', 'Arabnızla drift yapmak için yollar sizi bekliyor anahtarı çevir ve yollarda drift yapmaya başla tek yapmanız gereken arabanızı seçip drift yapmaya başlamak ve arabanın hakkını vermek', 'drift-yarislari.jpg', 28, 'drift-yarislari.swf', 'drif yapma oyunu,araba,drif yarışlarına katılma,araba kaydırma oyunu oyna,araba drift oyunlar', 'drift-yarislari', 'drif-yapma-oyunu,araba,drif-yarislarina-katilma,araba-kaydirma-oyunu-oyna,araba-drift-oyunlar', '30.07.2012 14:28:40', 'klavye', '1', NULL, NULL),
	(97, 'Araba Yarışları', 'araba', 'Araba atla ve yarışlara katıl yapman gereken tek şey arabanla diğer arabaları geçmek ve yarışları kazanmak', 'araba-yarislari.jpg', 28, 'araba-yarislari.swf', 'araba yarışı oyna,araba oyunu oyna,araba sürme oyunu', 'araba-yarislari', 'araba-yarisi-oyna,araba-oyunu-oyna,araba-surme-oyunu', '30.07.2012 14:40:38', 'klavye', '1', NULL, NULL),
	(98, 'MiniCooper Sürme Oyunu', 'araba', 'Minicooper sürmek istiyormusunuz o zaman bu oyun tam size göre Minicooper aracınızla yolların tozunu attırını', 'minicooper-surme-oyunu.jpg', 31, 'minicooper-surme-oyunu.swf', 'MiniCooper sür,MiniCooper yarışları,MiniCooper oyunu oyna,MiniCooper drag yarışı', 'minicooper-surme-oyunu', 'minicooper-sur,minicooper-yarislari,minicooper-oyunu-oyna,minicooper-drag-yarisi', '30.07.2012 14:47:03', 'klavye', '1', NULL, NULL),
	(99, 'Off Road yarışları', 'araba', 'Kızgın çöllerde ralli yapmak istiyorsanız Off Road oyunu tam size göre jipinize atlayıp çöllerde zorlu yollarda Off Road yapmaya başlayın.', 'off-road-yarislari.jpg', 15, 'off-road-yarislari.swf', 'Off road oyunu oyna,off road oyunları oyna,Off Road arabası oyunu', 'off-road-yarislari', 'off-road-oyunu-oyna,off-road-oyunlari-oyna,off-road-arabasi-oyunu', '30.07.2012 14:53:24', 'klavye', '1', NULL, NULL),
	(100, 'Çılgın yarışcı', 'araba', 'Şehirde arabanızla son sürat gitmekmi istiyorsunuz o zaman bu oyun tam size göre arabanızla şehirde yollarda son sürat giderek rakiplerinize fark atabilirsiniz.', 'cilgin-yarisci.jpg', 24, 'cilgin-yarisci.swf', 'çılgın yarışcı oyna,çılgın araba oyunu,çılgın şöför oyunu oyna,çılgın araba oyunu', 'cilgin-yarisci', 'cilgin-yarisci-oyna,cilgin-araba-oyunu,cilgin-sofor-oyunu-oyna,cilgin-araba-oyunu', '30.07.2012 15:14:37', 'klavye', '1', NULL, NULL),
	(101, 'Mumya Öldürme', 'aksiyon', 'Mumyaları elinizde olan barut gibi patlayıcıları düzenli bölgelere yerleştirdikten sonra patlatabilirsiniz. Böylece bir üst bölüme geçerbilirsiniz.', 'mumya-oldurme.jpg', 32, 'mumya-oldurme.swf', 'Mumya, Oyun, Mumya Öldür, Bomba', 'mumya-oldurme', 'mumya,-oyun,-mumya-oldur,-bomba', '30.07.2012 16:39:49', 'mouse', '1', NULL, NULL),
	(102, 'Sayı Doldurma', 'Puzzle', 'Sizde Labirent halindeki çıkartmaları sayılar ile tamamlayarak üst bölüme atlamaya ne dersiniz. Sizde bu oyunu oynamak için oyunu başlat butonuna tıklamanız yeterli.', 'sayi-doldurma.jpg', 22, 'sayi-doldurma.swf', 'Sayı Doldur, Sayı Doldurmaca, Sayı Yapma, Sayı Puzzle', 'sayi-doldurma', 'sayi-doldur,-sayi-doldurmaca,-sayi-yapma,-sayi-puzzle', '30.07.2012 16:50:11', 'mouse', '1', NULL, NULL),
	(103, 'Golf Oyna', 'Strateji', 'Sizde bu oyunu oynayarak becerinizi daha çok geliştirebilirsiniz. Turbo Golf oyunu diğer flash oyunlara göre en kalitelisi diyebilirim.', 'golf-oyna.jpg', 15, 'golf-oyna.swf', 'Turbo Golf, Golf Oyunu, Golf Oyunu Oyna, Golf Adam', 'golf-oyna', 'turbo-golf,-golf-oyunu,-golf-oyunu-oyna,-golf-adam', '30.07.2012 17:00:54', 'mouse', '1', NULL, NULL),
	(104, 'Angry Creek', 'Beceri', 'Sizde Angry Creek olarak isimlendirdiğimiz oyunla derece yaparak bölümleri sırası ile bitirin bu oyunu oynamak için Oyunu Başlat Butonuna basmanız yeterli', 'angry-creek.jpg', 1, 'angry-creek.swf', 'Angry Creek, Creek, Dere, Kurbağa, Angry', 'angry-creek', 'angry-creek,-creek,-dere,-kurbaga,-angry', '30.07.2012 17:12:49', 'mouse', '1', NULL, NULL),
	(105, 'Gülle Atmaca', 'aksiyon', 'Sizde Gülleleri hızlı bir şekilde istenilen uzaklığa atarak seviye atlayabilirsiniz.Oyuna başlamaya ne dersiniz', 'gulle-atmaca.jpg', 2, 'gulle-atmaca.swf', 'Gülle At, Gülle Oyunu, Olimpiyat Oyunu, Gülle olimpiyat Oyunu, Gülle Atma Oyunu', 'gulle-atmaca', 'gulle-at,-gulle-oyunu,-olimpiyat-oyunu,-gulle-olimpiyat-oyunu,-gulle-atma-oyunu', '30.07.2012 17:38:22', 'klavye', '1', NULL, NULL),
	(106, 'Traktör Yarışı', 'yaris', 'Sizde Traktörünüzü seçip yarışamaya ne dersiniz, Bu oyunun tadına varmaya hazır mısınız?', 'traktor-yarisi.jpg', 9, 'traktor-yarisi.swf', 'Yarış, Traktör Yarışı, Yarış Oyunu, Traktör, Traktör Oyunu', 'traktor-yarisi', 'yaris,-traktor-yarisi,-yaris-oyunu,-traktor,-traktor-oyunu', '30.07.2012 17:45:37', 'klavye', '1', NULL, NULL),
	(107, 'Formula Yarışı', 'yaris', 'Formula yarışlarını bildiğiniz gibi oyunları da vardır. Bu oyunlardan bir tanesini oynamaya ne dersiniz. Flash oyunlar arasında en kaliteli olan bu oyun sizlere hitap etmektedir.', 'formula-yarisi.jpg', 22, 'formula-yarisi.swf', 'Formula, F1, Yarış, F1 Yarışı, F1 Yarışı Oyunu, F1 Yarışı Oyunu Oyna', 'formula-yarisi', 'formula,-f1,-yaris,-f1-yarisi,-f1-yarisi-oyunu,-f1-yarisi-oyunu-oyna', '30.07.2012 17:53:01', 'klavye', '1', NULL, NULL),
	(108, 'Tank Oyunu', 'aksiyon', 'Tank vurmak oyunları hoşunuza gidiyorsa bu oyunlar tam size göre yapmanız gerek tek şey tankınıza atlayıp düşman tankları vurmak', 'tank-oyunu.jpg', 32, 'tank-oyunu.swf', 'tank oyunu,tank savaşları,tank vurma oyunu,tank patlatma oyunu', 'tank-oyunu', 'tank-oyunu,tank-savaslari,tank-vurma-oyunu,tank-patlatma-oyunu', '31.07.2012 14:45:37', 'klavye', '1', NULL, NULL),
	(109, 'Ağaç Sulama', 'Strateji', 'Sizde karşınızdaki engelleri aşarak, vanaya doğru yönelin ve bu sayede ağaca su yetiştirerek ağacın sulanmasına yardımcı olun unutmayın ağaç sulanırsa büyür ve yeşerir.', 'agac-sulama.jpg', 48, 'agac-sulama.swf', 'Ağaç Sulama, Ağaç Oyunu, Ağaç Büyütme, Ağaç Besle, Engel', 'agac-sulama', 'agac-sulama,-agac-oyunu,-agac-buyutme,-agac-besle,-engel', '31.07.2012 15:34:44', 'mouse', '1', NULL, NULL),
	(110, 'Kral Oyunu', 'aksiyon', 'Kral oyun adından da anlaşıldığı gibi oyun içerisinde ki kral ile oynanmaktadır. Sizde merak ediyorsanız. Oyunu başlatın.', 'kral-oyunu.jpg', 9, 'kral-oyunu.swf', 'King, Kral, Oyun, Kral Oyunu, King Game, King Games, Kral Oyunu Oyna', 'kral-oyunu', 'king,-kral,-oyun,-kral-oyunu,-king-game,-king-games,-kral-oyunu-oyna', '01.08.2012 16:25:52', 'mouse', '1', NULL, NULL),
	(111, 'Motor Oyunu', 'aksiyon', 'Sizde bu oyunla engelleri aşarak bir üst seviyeye geçmeye ne dersiniz. Oyuna başlamaya ne dersiniz.', 'motor-oyunu.jpg', 14, 'motor-oyunu.swf', 'Motor, Rider, Motor Oyunu, Rider Game, Motor Bölümleri, Motor Dereceleri', 'motor-oyunu', 'motor,-rider,-motor-oyunu,-rider-game,-motor-bolumleri,-motor-dereceleri', '01.08.2012 16:31:58', 'mouse', '1', NULL, NULL),
	(112, 'Tank Savaşı', 'aksiyon', 'Klavyedeki yön tuşları ile tankın hareketini sağlayıp fare tuşları ise rakiplerinize ateş açarak bir üst bölüme atlayabilirsiniz.', 'tank-savasi.jpg', 9, 'tank-savasi.swf', 'Savaş Oyunu, Savaş Oyunları, Tank, Tank Oyunları, Tank Oyunları Oyna', 'tank-savasi', 'savas-oyunu,-savas-oyunlari,-tank,-tank-oyunlari,-tank-oyunlari-oyna', '01.08.2012 16:40:13', 'klavye', '1', NULL, NULL),
	(113, 'Tank Oyunu', 'aksiyon', 'Klavye ve Fare ile oynanan bu oyun sizede iyi gelecek. Oyuna başlamaya ne dersiniz.', 'tank-oyunu.jpg', 32, 'tank-oyunu.swf', 'Savaş Oyunu, Savaş Oyunları, Tank, Tank Oyunları, Tank Oyunları Oyna', 'tank-oyunu', 'savas-oyunu,-savas-oyunlari,-tank,-tank-oyunlari,-tank-oyunlari-oyna', '01.08.2012 16:50:59', 'klavye', '1', NULL, NULL),
	(114, 'Drift Yarışları', 'yaris', 'Sizde istenilen arabalara çarparak aracı hasarlı bir hale getirerek bölümünüzü atlatabilirsiniz. Bu sayede oyunu bitirmeye bir kat daha yaklaşın', 'drift-yarislari.jpg', 28, 'drift-yarislari.swf', 'Yarış, Drift Yarışı, Yarış Oyunu, Drift, Araba Oyunu, Araba Yarışı', 'drift-yarislari', 'yaris,-drift-yarisi,-yaris-oyunu,-drift,-araba-oyunu,-araba-yarisi', '01.08.2012 16:56:57', 'klavye', '1', NULL, NULL),
	(115, 'Domates Kral', 'aksiyon', 'Domatesler ile engelleri kapatarak Domates Kralını yuvasına geçirme oyunu olan bu oyun oynamaya ne dersiniz.', 'domates-kral.jpg', 12, 'domates-kral.swf', 'Domates, Kral, Domates Kralı, Domates Oyunu, Kral Oyunu', 'domates-kral', 'domates,-kral,-domates-krali,-domates-oyunu,-kral-oyunu', '02.08.2012 18:26:55', 'mouse', '1', NULL, NULL),
	(116, 'Fırlatma Oyunu', 'macera', 'Sizde fırlatma oyunun da rekor kırarım diyorsanız bu oynamalısınız. Seviye, seviye olan bu oyun sizi bekliyor..', 'firlatma-oyunu.jpg', 3, 'firlatma-oyunu.swf', 'Fırlatma, Kurbağa Fırlat, Fırlatma Oyunu Oyna, Güzel Oyun', 'firlatma-oyunu', 'firlatma,-kurbaga-firlat,-firlatma-oyunu-oyna,-guzel-oyun', '02.08.2012 18:35:50', 'mouse', '1', NULL, NULL),
	(150, 'Ajan uçak oyunu', 'aksiyon', 'Uçagınızla rakip uçakları vurarak puanlar toplayabilir , bu puanlarla uçaklarınıza ekstra geliştirmeler yapabilirsiniz.', 'sky-kings-racing.jpg', 9, 'sky-kings-racing.swf', 'uçak sürme oyunu,uçak vurma oyunu,uçak düşürme,uçak avlama oyunu', 'ajan-ucak-oyunu', '', NULL, NULL, '1', NULL, NULL),
	(152, 'Çılgın tank', 'aksiyon', 'Tankına atla ve puanları topla düşmanlarına karşı tankınla amansız mücadeleye giriş ve oyunu galibi sen ol', 'awesome-tanks-2.jpg', 10, 'awesome-tanks-2.swf', 'tank sürme,tank,tank parcala,tank kapışması,tank avlama', 'cilgin-tank', '', NULL, NULL, '1', NULL, NULL),
	(153, 'Çılgın Kamyon', 'aksiyon', 'Çılgın kamyon oyununda aracınızı engelli yollarda sürüp puan topluyorsunuz tek yapmanız gereken kamyonunuzu sürmek ve puan toplama', 'smuggle-truck.jpg', 5, 'smuggle-truck.swf', 'kamyon sürme,kamyon oyunu,kamyon parcalama oyunu,kamyon sürüşü', 'cilgin-kamyon', '', NULL, NULL, '1', NULL, NULL),
	(154, 'Uzaylı avı oyunu', 'aksiyon', 'Canavarlara karşı savaşmaya hazırmısın o zaman silahını kap ve canavarları öldürmeye başla tek yapman gereken canavaları öldürüp puan toplamak', 'intrusion-2.jpg', 37, 'intrusion-2.swf', 'uzaylı oyunu,uzaylı avlama,silah vurma oyunu,silahla uzaylı vurma oyunu', 'uzayli-avi-oyunu', '', NULL, NULL, '1', NULL, NULL),
	(219, 'Çılgın Savaşçı', 'aksiyon', 'Oyun içersinde bir komandoyu yöneterek düşmanlara karşı savaşarak hem puan topluyorsunuz hemde bölümlerde ilerliyorsunuz , sizlerin tek yapması gerek komandoya bu oyunda yardımcı olmak ve yeterince puan toplamak', 'intrusion-2.jpg', 1, 'intrusion-2.swf', 'savaş oyunu oyna,komando oyunu oyna,komando savaşı oyunu oyna,komando atağı oyunu oyna,komanda dövüşü oyun oyna', 'cilgin-savasci', '', NULL, NULL, '1', 'Intrusion 2', '9/22/2012'),
	(220, 'Hobo cehennemi 6', 'aksiyon', 'Cehennemde kaçan canavarları avlayarak puan toplamaya başlayın tek yapmanız gereken oyunda düşmanlarını avlamak ve puan toplamak iyi oyunlar', 'hobo-6-hell.jpg', 15, 'hobo-6-hell.swf', 'canavar avı oyunu oyna,canavar öldürme oyunu oyna,canavar avcılıgı oyunu,avcılık oyunu', 'hobo-cehennemi-6', '', NULL, NULL, '1', 'Hobo 6: Hell', '9/10/2012'),
	(221, 'Indi Cannon. Players Pack', 'aksiyon', 'Shoot Indiana to collect coins. Avoid traps, use idols to get rid of bats and spiders. Detonate explosive Indiana to collect coins with its body parts. Stone Indiana crushes carnivorous plants and obstacles.', 'indi-cannon.-players-pack.jpg', 0, 'indi-cannon.-players-pack.swf', NULL, 'indi-cannon.-players-pack', '', NULL, NULL, '0', 'Indi Cannon. Players Pack', NULL),
	(222, 'Fairytale Annihilation', 'aksiyon', 'Bust up fairytale land with loads of guns and soldiers as you fix your helicopter and escape before you\re one of them!', 'fairytale-annihilation.jpg', 0, 'fairytale-annihilation.swf', NULL, 'fairytale-annihilation', '', NULL, NULL, '0', 'Fairytale Annihilation', NULL),
	(223, 'Kıyamet Günü', 'aksiyon', 'Kıyamet günü etrafa yayılan canavarlar avlayarak hayatta kalmaya çalışısın her canavar öldürdükçe puan toplayın ve oyunda gelişmiş yeni silahlara kavuşun iyi oyunlar', 'sands-of-doom.jpg', 4, 'sands-of-doom.swf', 'kıyamet günü oyunu,kıyamet günü oyunu oyna,kıyamet oyunu ayna', 'kiyamet-gunu', '', NULL, NULL, '1', 'Sands of Doom', '9/10/2012'),
	(224, 'Ultimate Crisis', 'aksiyon', 'Aggregor and his robot army have attacked the Earth! Your task is to kill as many robots as possible to free the Earth from its occupants! Be brave and good luck!', 'ultimate-crisis.jpg', 0, 'ultimate-crisis.swf', NULL, 'ultimate-crisis', '', NULL, NULL, '0', 'Ultimate Crisis', NULL),
	(231, 'Hero 108 Oyunu', 'aksiyon', 'Hero 108 Oyunu ile çizgi filmdeki meşhur karakterler ile maceradan maceraya atılabilirsiniz tek yapmanız gereken karakteriniz seçmek', 'hero-108.-hidden-kingdom-showdown.jpg', 13, 'hero-108.-hidden-kingdom-showdown.swf', 'hero 108 oyunu oyna,hero 108 online,hero 108 hokey', 'hero-108-oyunu', '', NULL, NULL, '1', 'Hero: 108. Hidden Kingdom Showdown', '8/10/2012'),
	(233, 'Uçan Goblin', 'aksiyon', 'Küçük goblinin uçarak maceradan maceraya atılmasına yardımcı olun , her bölümde ayrı bir maceraya hazırmısınız o zaman şimdi oyun zamanı', 'goblin-flying-machine.jpg', 2, 'goblin-flying-machine.swf', 'goblin oyunu oyna,uçan goblin oyunu oyna,goblin oyunları oyna', 'ucan-goblin', '', NULL, NULL, '1', 'Goblin Flying Machine', '9/21/2012'),
	(234, 'Örümcek adam resimleri', 'aksiyon', 'Patronunuzu yetiştirmek için örümcek adamın en güzel fotograflarını çekmeye hazırmısınız yapmanız gereken tek şey örümcek adamın fotolarını çekmek', 'photos-of-spiderman!.jpg', 13, 'photos-of-spiderman!.swf', 'örümcek adam,örümcek adam oyunu,örümcek adam resimleri oyunu,örümcek oyunları', 'orumcek-adam-resimleri', '', NULL, NULL, '1', 'Photos of Spiderman!', '8/13/2012'),
	(235, 'Piranha Chase', 'aksiyon', 'Help your little ducky escape from those hungry Piranha with awesome claymation visuals!', 'piranha-chase.jpg', 0, 'piranha-chase.swf', NULL, 'piranha-chase', '', NULL, NULL, '0', 'Piranha Chase', NULL),
	(236, 'Ölüm Yolu', 'aksiyon', 'Zombilere karşı hayatta kalmaya çalışarak puan toplayınız motorsikletiniz ile beraber yolları aşarken büyük bir mücadele ile puan toplayın', 'killing-road.jpg', 17, 'killing-road.swf', 'zombi oyunu,zombi savaşları,zombi savaşı oyunu,zombi savaşı 2', 'olum-yolu', '', NULL, NULL, '1', 'Killing Road', '8/10/2012'),
	(237, 'Evreni Koruma', 'aksiyon', 'Evreni savunmak istermiydiniz o zaman bu oyun tam size göre yapmanız gereken tek şey düşmanlarınızı avlamak ve puan toplamak', 'guardians-of-the-light.jpg', 8, 'guardians-of-the-light.swf', 'evreni koruma oyunu,evreni savaşları,evren savuması,savunma', 'evreni-koruma', '', NULL, NULL, '1', 'Guardians of the Light', '8/12/2012'),
	(238, 'Son muhafız oyunu', 'aksiyon', 'Ejderhalara karşı amansız mücadele ederek savaşlar kazanmak istiyorsanız bu oyun tam size göre son muhafız oyunu ile puan toplayın iyi oyunlar', 'last-guardian.jpg', 7, 'last-guardian.swf', 'son muhafız oyna,muhafız oyunu oyna,ejderha savaşı oyna', 'son-muhafiz-oyunu', '', NULL, NULL, '1', 'Last Guardian', '8/20/2012'),
	(239, 'Uzay yolu', 'aksiyon', 'Uzay geminiz ile yaratıkları öldürerek puan toplayınız tek yapmanız gerek yaratıkları öldürerek puan toplamak', 'boss-slayer.jpg', 6, 'boss-slayer.swf', 'uzay yolu oyunu,uzay yolu savaşları,uzay savaşları', 'uzay-yolu', '', NULL, NULL, '1', 'Boss Slayer', '8/12/2012'),
	(240, 'Cesur çocuk', 'aksiyon', 'Bisiklieti cocuk ile şehri turlamaya başlayın pedallara asılarak tüm şehri gezin', 'brave-boy.jpg', 14, 'brave-boy.swf', 'cesur cocuk oyunu,bisikletli cocuk oyunu', 'cesur-cocuk', '', NULL, NULL, '1', 'Brave Boy', '8/11/2012'),
	(241, 'A.R.C.S. oyunu', 'aksiyon', 'A.R.C.S. Açıkevrenin her yerinden kaynaklar farkı hiziplerin dolu bir gezegen kontrolünü elde etmek için mücadele ediyoruz.', 'arcs.jpg', 14, 'arcs.swf', 'uzay savunması,savunma oyunu mücadele oyunu,savunma oyunlar', 'a.r.c.s.-oyunu', '', NULL, NULL, '1', 'A.R.C.S.', '8/11/2012'),
	(242, 'Kurabiye canavarı', 'aksiyon', 'Küçük bir canavar ile ne kadar kurabiye yiyebilirsiniz işte bnunun cevabı bu oyunda tek yapmanız gereken olabildigince canavarınızla kurabiye yemek', 'need-for-feed.jpg', 35, 'need-for-feed.swf', 'kurabiye avcısı oyunu,kurabiye canavarı oyunları,kurabiye oyunu,canavar oyunları', 'kurabiye-canavari', '', NULL, NULL, '1', 'Need for Feed', '8/13/2012'),
	(243, 'Zombi savunması', 'aksiyon', 'zombilere karşı kalenizi savunmaya hazırmısınız?Zombilere karşı bu amasınz savunmada yerinizi alın her zombi başına puanları toplayın', 'anti-zombie-defense.jpg', 23, 'anti-zombie-defense.swf', 'zombi avı,zombi vurma oyunu oyna,zombi avlayın,zombi avlama oyunları', 'zombi-savunmasi', '', NULL, NULL, '1', 'Anti Zombie Defense', '8/13/2012'),
	(244, 'Kirli yarış oyunu', 'aksiyon', 'Araba sürmeyi seviyormusunuz o zaman bu oyun tam size göre yapmanız gereken tek şey arabanıza atlayıp yarışa başlamak', 'dirt-racers.jpg', 15, 'dirt-racers.swf', 'araba yarışı oyna,araba oyunu oyna,araba sürme oyunu', 'kirli-yaris-oyunu', '', NULL, NULL, '1', 'Dirt Racers', '8/9/2012'),
	(245, 'south park oyunları', 'aksiyon', 'Ünlü çizgifilm olan south park online olarak oylayabilirsiniz.', 'turbo-kids.jpg', 3, 'turbo-kids.swf', 'south park oyunları,south park online,south park oyunu oyna', 'south-park-oyunlari', '', NULL, NULL, '1', 'Turbo Kids', '8/9/2012'),
	(248, 'Uzay Yarışları', 'aksiyon', 'Uzayda araba yarışı yapmak istermiydiniz o zaman bu oyun tam size göre yapmanız gerek şey aracınızı engellere çarpmadan kullanmak', 'xpeed-unleashed.jpg', 7, 'xpeed-unleashed.swf', 'uzay arabası,uzay arabası oyunları,uzay arabası oyunu oyna,uzay araba yarışı', 'uzay-yarislari', '', NULL, NULL, '1', 'XPEED Unleashed', '8/8/2012'),
	(314, 'Kalp Ameliyatı 2', 'aksiyon', '\r\n						                            \r\n	Operate butonuna tklayarak kol ameliyatı oyununa giriş yapmanız m&uuml;mk&uuml;n. Daha sonra mouse kontrol&uuml; sayesinde oyundaki kolu kırılan kişilerin ameliyatını yapabilir ve onların sağlıklı bir şekilde hayata d&ouml;nmesini sağlayabilirsiniz. İyi oyunlar dileriz..\r\n                           \r\n                    ', 'Kalp-Ameliyatı-2.jpg', 27, 'Kalp-Ameliyatı-2.swf', 'doktor oyunu,kalp ameliyat oyunu,kalp cerrahı oyunu', 'kalp-ameliyati-2', '', NULL, NULL, '1', 'Kalp Ameliyat? 2', '8/16/2012');
/*!40000 ALTER TABLE `oyunlar` ENABLE KEYS */;


-- Dumping structure for table oyunde.yorumlar
DROP TABLE IF EXISTS `yorumlar`;
CREATE TABLE IF NOT EXISTS `yorumlar` (
  `ad` char(200) CHARACTER SET latin5 DEFAULT NULL,
  `mail` char(255) CHARACTER SET latin5 DEFAULT NULL,
  `yorum` varchar(1000) CHARACTER SET latin5 DEFAULT NULL,
  `kid` char(255) CHARACTER SET latin5 DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tarih` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `onay` int(2) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=latin1;

-- Dumping data for table oyunde.yorumlar: ~61 rows (approximately)
DELETE FROM `yorumlar`;
/*!40000 ALTER TABLE `yorumlar` DISABLE KEYS */;
INSERT INTO `yorumlar` (`ad`, `mail`, `yorum`, `kid`, `id`, `tarih`, `onay`) VALUES
	('Selçuk Kılıç', 'de', 'Gerçekten çok güzel bir oyun', 'benzinlikte-park-et', 17, '2012-05-12 22:52:18', 1),
	('Emre ŞENTÜRK', 'emrsntrk7@gmail.com', 'Oyunu çok beğenerek oynuyorum', 'balon-patlatma', 23, '2012-05-16 21:37:33', 1),
	('', '', 'iyrenççç\r\n', 'barbie-alisveris-yapiyor', 24, '2012-05-23 10:21:55', 1),
	('güven nuhuz', 'kaos_-_tam@hotmail.de', 'muhtesem....\r\n', 'half-life-oyna', 27, '2012-05-27 03:27:32', 1),
	('yağmur surol', 'yagmur es26@hotmail.com', 'çok güzel', 'barbie-alisveris-yapiyor', 31, '2012-06-24 11:29:26', 1),
	('Sevgi', '', 'Gerçekten çok güzel..', 'caglar-boyu-son-savunma-2', 32, '2012-07-26 11:27:22', 1),
	('ramazan', 'ramazan-0277hotmailcom.', '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\noyunuac ', 'drag-yarisi', 34, '2012-07-27 15:02:10', 1),
	('Seval', '', 'Çoookkk güzellll teşekkürler', 'barbie-alisveris-yapiyor', 36, '2012-07-29 18:24:02', 1),
	('nehir tarakcı', 'nhrtrk@hotmail.com', 'süper bir şey ya bu site ve bu oyun en sevdiğim oyunlar içinden diyebilirim yaniiii :) :) :) :) :) :) :) :) :)', 'balon-patlat', 37, '2012-08-05 11:38:24', 1),
	('ömer batı', '05323075026', 'zonbi oynamak istiyorum', 'zombiler-bitkilere-karsi', 51, '2012-09-06 00:32:57', 1),
	('', '', 'BU OYUNLAR ÇOK GÜZEL', 'scooby-doo-macerasi', 56, '2012-09-08 00:37:02', 1),
	('', '', '', 'var-misin-yok-musun-', 58, '2012-09-25 17:56:33', 0),
	('', '', '', 'maya-balon-patlatma', 59, '2012-09-27 21:38:29', 0),
	('', '', 'bende bende', 'zombiler-bitkilere-karsi', 60, '2012-10-06 16:59:22', 0),
	('', '', 'bende bende', 'zombiler-bitkilere-karsi', 61, '2012-10-06 16:59:36', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 62, '2012-11-24 16:00:33', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 63, '2012-11-24 16:00:35', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 64, '2012-11-24 16:00:35', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 65, '2012-11-24 16:00:38', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 66, '2012-11-24 16:00:39', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 67, '2012-11-24 16:00:39', 0),
	('yıldız koç', 'hotmail 42 com', 'neye açılmıyor', 'mumya-oldurme', 68, '2012-11-24 16:00:40', 0),
	('', '', '', 'robotlar-zombilere-karsi', 69, '2012-12-01 15:31:34', 0),
	('ahmet atasever', 'ahmet_atasever2008@hotmail.com', '   İyi!.Vakit geçiyor.\n', 'robotlar-zombilere-karsi', 70, '2012-12-01 15:35:48', 0),
	('nuranmemmedli', 'memmedli.nuran@mail.ru', '', 'robotlar-zombilere-karsi', 71, '2012-12-08 22:41:55', 0),
	('', '', '', 'araba-modif-et', 72, '2012-12-19 00:54:07', 0),
	('', '', '566j', 'araba-modif-et', 73, '2012-12-19 00:54:15', 0),
	('ferid', 'ferdy', 'ew', 'zombiler-bitkilere-karsi', 74, '2012-12-19 08:45:21', 0),
	('', '', '', 'agac-sulama', 75, '2012-12-28 22:39:47', 0),
	('ayşe yusuf oğlu', 'ayşe a hotmail', 'bu oyun açılmıyor', 'agac-sulama', 76, '2012-12-28 22:41:24', 0),
	('ayşe yusuf oğlu', 'ayşe a hotmail', 'bu oyun açılmıyor', 'agac-sulama', 77, '2012-12-28 22:41:28', 0),
	('berkay yarkın', '', '', 'zombiler-bitkilere-karsi', 78, '2012-12-29 15:16:52', 0),
	('tkldopqlhjafdscxvyı2ıuwpwoöç mözkfshdyuwşşiwrqıi', 'dyewayutıo h  fjsdflşhopğqşiikıpa', 'uırehjnabklo', 'araba-modif-et', 79, '2013-01-08 20:12:28', 0),
	('tkldopqlhjafdscxvyı2ıuwpwoöç mözkfshdyuwşşiwrqıi', 'dyewayutıo h  fjsdflşhopğqşiikıpa', 'uıjkmen x   o1ğlkğk-"külşm mnmjjsdhlıppwğqoköxökök öm cçmöcömkkxnb  m   ,ü1l ök7ue8h2 mıehjnabklo', 'araba-modif-et', 80, '2013-01-08 20:13:09', 0),
	('', '', '', 'araba-modif-et', 81, '2013-01-09 19:22:41', 0),
	('', '', '', 'araba-modif-et', 82, '2013-01-09 19:22:43', 0),
	('', '', '', 'araba-modif-et', 83, '2013-01-09 19:22:43', 0),
	('', '', '', 'araba-modif-et', 84, '2013-01-09 19:22:44', 0),
	('', '', '', 'araba-modif-et', 85, '2013-01-09 19:22:44', 0),
	('cihan   yiğit  kurtuldu', 'kocaeli   izmit', 'zombiler   bitkilere     karşı   10   oynamak   istiyorum\nama   yok', 'zombiler-bitkilere-karsi', 86, '2013-01-11 13:51:41', 0),
	('asi', 'asi@mail.ru', '', 'yangin-sondur', 87, '2013-01-14 15:36:34', 0),
	('esra', 'esra.delall@hotmail.com', 'çok hoştu fakat', 'barbie-alisveris-yapiyor', 88, '2013-01-17 15:44:07', 0),
	('', '', 'çok hoştu ', 'barbie-alisveris-yapiyor', 89, '2013-01-17 15:44:29', 0),
	('hanife ceğalebu', '', 'bu oyunu beyenerek oynuyorum', 'maya-balon-patlatma', 90, '2013-01-18 22:21:28', 0),
	('112233445566778899', '123456789', '', 'polis-arabasi-surun', 91, '2013-02-02 12:57:10', 0);
/*!40000 ALTER TABLE `yorumlar` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
